ASM = nasm
ASMFLAGS = -f elf64
LD = ld
LDFLAGS =

SRC = src/REPLACE_THIS.asm
OBJ = build/REPLACE_THIS.o
BIN = build/REPLACE_THIS

all: $(BIN)

$(OBJ): $(SRC)
	mkdir -p build
	$(ASM) $(ASMFLAGS) $< -o $@

$(BIN): $(OBJ)
	$(LD) $^ -o $@

run: all
	./$(BIN)

clean:
	rm -rf build